// ─── Mock Data ───────────────────────────────────────────────────────────────

export const MOCK_STATS = {
  users: {
    total: 12543,
    active: 9821,
    verified: 8234,
    newToday: 156,
    newThisMonth: 1243,
    male: 6821,
    female: 5722,
  },
  memberships: { premium: 2341, elite: 892, totalPaid: 3233 },
  interests:   { total: 34521, accepted: 12430, pending: 22091 },
  matches:     { total: 8234 },
  revenue:     { total: 4823500, thisMonth: 342100 },
};

export const MOCK_USERS = [
  {
    _id: "1",
    fullName: "Rajesh Kumar",
    email: "rajesh@example.com",
    mobile: "+91 98765 43210",
    gender: "Male",
    age: 28,
    city: "Bangalore",
    state: "Karnataka",
    isVerified: true,
    isActive: true,
    role: "user",
    membership: {
      plan: "premium",
      isActive: true,
      amount: 4999,
      startDate: "2024-01-15",
      endDate: "2024-07-15",
    },
    profileViews: 245,
    interests: 18,
    lastActive: "2 hours ago",
    joinedDate: "2024-01-15",
    about: "Looking for a life partner who shares similar values and interests.",
    height: "5'10\"",
    maritalStatus: "Never Married",
    religion: "Hindu",
    motherTongue: "Hindi",
    education: "B.Tech in Computer Science",
    occupation: "Software Engineer",
    company: "Tech Corp",
    annualIncome: "₹15-20 LPA",
    familyType: "Nuclear Family",
    fathersOccupation: "Business",
    mothersOccupation: "Homemaker",
    siblings: "1 Brother",
    verificationMethod: "Aadhaar eKYC",
    verifiedOn: "2024-01-16",
    paymentHistory: [
      { label: "Premium Plan - 6 Months", date: "January 15, 2024", amount: "₹4,999" },
    ],
  },
  {
    _id: "2",
    fullName: "Priya Sharma",
    email: "priya@example.com",
    mobile: "+91 98765 43211",
    gender: "Female",
    age: 26,
    city: "Mumbai",
    state: "Maharashtra",
    isVerified: true,
    isActive: true,
    role: "user",
    membership: {
      plan: "elite",
      isActive: true,
      amount: 9999,
      startDate: "2024-02-10",
      endDate: "2025-02-10",
    },
    profileViews: 312,
    interests: 25,
    lastActive: "1 hour ago",
    joinedDate: "2024-02-10",
    about: "Looking for a caring and understanding partner.",
    height: "5'4\"",
    maritalStatus: "Never Married",
    religion: "Hindu",
    motherTongue: "Marathi",
    education: "MBA",
    occupation: "Marketing Manager",
    company: "StartupX",
    annualIncome: "₹12-15 LPA",
    familyType: "Joint Family",
    fathersOccupation: "Teacher",
    mothersOccupation: "Doctor",
    siblings: "1 Sister",
    verificationMethod: "Aadhaar eKYC",
    verifiedOn: "2024-02-11",
    paymentHistory: [
      { label: "Elite Plan - 1 Year", date: "February 10, 2024", amount: "₹9,999" },
    ],
  },
  {
    _id: "3",
    fullName: "Amit Verma",
    email: "amit@example.com",
    mobile: "+91 98765 43212",
    gender: "Male",
    age: 30,
    city: "Delhi",
    state: "Delhi",
    isVerified: false,
    isActive: false,
    role: "user",
    membership: { plan: "free", isActive: false, amount: 0, startDate: null, endDate: null },
    profileViews: 89,
    interests: 5,
    lastActive: "3 days ago",
    joinedDate: "2024-03-05",
    about: "Simple person looking for a simple life.",
    height: "5'8\"",
    maritalStatus: "Never Married",
    religion: "Hindu",
    motherTongue: "Hindi",
    education: "B.Com",
    occupation: "Accountant",
    company: "CA Firm",
    annualIncome: "₹5-8 LPA",
    familyType: "Nuclear Family",
    fathersOccupation: "Retired",
    mothersOccupation: "Homemaker",
    siblings: "None",
    verificationMethod: "—",
    verifiedOn: "—",
    paymentHistory: [],
  },
  {
    _id: "4",
    fullName: "Sneha Patel",
    email: "sneha@example.com",
    mobile: "+91 98765 43213",
    gender: "Female",
    age: 27,
    city: "Ahmedabad",
    state: "Gujarat",
    isVerified: true,
    isActive: true,
    role: "user",
    membership: {
      plan: "premium",
      isActive: true,
      amount: 4999,
      startDate: "2024-01-20",
      endDate: "2024-07-20",
    },
    profileViews: 421,
    interests: 32,
    lastActive: "30 mins ago",
    joinedDate: "2024-01-20",
    about: "Fun-loving and family-oriented.",
    height: "5'3\"",
    maritalStatus: "Never Married",
    religion: "Hindu",
    motherTongue: "Gujarati",
    education: "BDS",
    occupation: "Dentist",
    company: "City Dental Clinic",
    annualIncome: "₹10-12 LPA",
    familyType: "Nuclear Family",
    fathersOccupation: "Business",
    mothersOccupation: "Business",
    siblings: "1 Brother",
    verificationMethod: "Aadhaar eKYC",
    verifiedOn: "2024-01-21",
    paymentHistory: [
      { label: "Premium Plan - 6 Months", date: "January 20, 2024", amount: "₹4,999" },
    ],
  },
  {
    _id: "5",
    fullName: "Rahul Singh",
    email: "rahul@example.com",
    mobile: "+91 98765 43214",
    gender: "Male",
    age: 29,
    city: "Pune",
    state: "Maharashtra",
    isVerified: true,
    isActive: true,
    role: "admin",
    membership: {
      plan: "elite",
      isActive: true,
      amount: 9999,
      startDate: "2024-02-15",
      endDate: "2025-02-15",
    },
    profileViews: 198,
    interests: 15,
    lastActive: "5 hours ago",
    joinedDate: "2024-02-15",
    about: "Engineer by profession, traveler by passion.",
    height: "6'0\"",
    maritalStatus: "Never Married",
    religion: "Hindu",
    motherTongue: "Hindi",
    education: "M.Tech",
    occupation: "Senior Engineer",
    company: "Infosys",
    annualIncome: "₹20-25 LPA",
    familyType: "Nuclear Family",
    fathersOccupation: "Engineer",
    mothersOccupation: "Teacher",
    siblings: "None",
    verificationMethod: "Aadhaar eKYC",
    verifiedOn: "2024-02-16",
    paymentHistory: [
      { label: "Elite Plan - 1 Year", date: "February 15, 2024", amount: "₹9,999" },
    ],
  },
  {
    _id: "6",
    fullName: "Kavya Nair",
    email: "kavya@example.com",
    mobile: "+91 98765 43215",
    gender: "Female",
    age: 24,
    city: "Kochi",
    state: "Kerala",
    isVerified: true,
    isActive: true,
    role: "user",
    membership: { plan: "free", isActive: false, amount: 0, startDate: null, endDate: null },
    profileViews: 156,
    interests: 9,
    lastActive: "1 day ago",
    joinedDate: "2024-03-01",
    about: "Aspiring artist looking for her muse.",
    height: "5'2\"",
    maritalStatus: "Never Married",
    religion: "Christian",
    motherTongue: "Malayalam",
    education: "BFA",
    occupation: "Graphic Designer",
    company: "Freelance",
    annualIncome: "₹4-6 LPA",
    familyType: "Nuclear Family",
    fathersOccupation: "Businessman",
    mothersOccupation: "Nurse",
    siblings: "2 Brothers",
    verificationMethod: "Aadhaar eKYC",
    verifiedOn: "2024-03-02",
    paymentHistory: [],
  },
];

export const MOCK_MEMBERSHIPS = [
  {
    _id: "1",
    fullName: "Rajesh Kumar",
    email: "rajesh@example.com",
    mobile: "+91 98765 43210",
    membership: { plan: "premium", isActive: true, amount: 4999, startDate: "2024-01-15", endDate: "2024-07-15" },
  },
  {
    _id: "2",
    fullName: "Priya Sharma",
    email: "priya@example.com",
    mobile: "+91 98765 43211",
    membership: { plan: "elite", isActive: true, amount: 9999, startDate: "2024-02-10", endDate: "2025-02-10" },
  },
  {
    _id: "4",
    fullName: "Sneha Patel",
    email: "sneha@example.com",
    mobile: "+91 98765 43213",
    membership: { plan: "premium", isActive: true, amount: 4999, startDate: "2024-01-20", endDate: "2024-07-20" },
  },
  {
    _id: "5",
    fullName: "Rahul Singh",
    email: "rahul@example.com",
    mobile: "+91 98765 43214",
    membership: { plan: "elite", isActive: false, amount: 9999, startDate: "2023-02-15", endDate: "2024-02-15" },
  },
  {
    _id: "6",
    fullName: "Karthik Iyer",
    email: "karthik@example.com",
    mobile: "+91 98765 43216",
    membership: { plan: "premium", isActive: true, amount: 4999, startDate: "2024-03-01", endDate: "2024-09-01" },
  },
];

export const MOCK_INTERESTS = [
  {
    _id: "i1",
    sender:   { fullName: "Rajesh Kumar", id: "#1001" },
    receiver: { fullName: "Priya Sharma", id: "#1002" },
    matchScore: 92,
    status: "accepted",
    createdAt: "2024-03-17 10:30 AM",
  },
  {
    _id: "i2",
    sender:   { fullName: "Amit Verma",   id: "#1003" },
    receiver: { fullName: "Sneha Patel",  id: "#1004" },
    matchScore: 87,
    status: "pending",
    createdAt: "2024-03-17 09:15 AM",
  },
  {
    _id: "i3",
    sender:   { fullName: "Karthik Iyer", id: "#1005" },
    receiver: { fullName: "Anjali Gupta", id: "#1006" },
    matchScore: 95,
    status: "accepted",
    createdAt: "2024-03-16 04:20 PM",
  },
  {
    _id: "i4",
    sender:   { fullName: "Rohan Mehta",  id: "#1007" },
    receiver: { fullName: "Kavya Singh",  id: "#1008" },
    matchScore: 78,
    status: "declined",
    createdAt: "2024-03-16 02:45 PM",
  },
  {
    _id: "i5",
    sender:   { fullName: "Vikram Reddy", id: "#1009" },
    receiver: { fullName: "Divya Nair",   id: "#1010" },
    matchScore: 85,
    status: "pending",
    createdAt: "2024-03-16 11:30 AM",
  },
];

export const MOCK_VERIFICATIONS = [
  {
    _id: "v1",
    user: { _id: "1", fullName: "Rajesh Kumar", email: "rajesh.kumar@email.com", mobile: "+91 98765 43210", gender: "Male" },
    userId: "#1001", docNumber: "XXXX XXXX 4321", dob: "15/08/1995", gender: "Male",
    fathersName: "Suresh Kumar",
    address: "#123, MG Road, Koramangala, Bangalore - 560095",
    state: "Karnataka", pincode: "560095", age: 28,
    verifiedAt: "2024-03-17 10:30 AM",
    otpVerified: true, uidaiValidated: true, biometricMatch: true, autoApproved: true,
  },
  {
    _id: "v2",
    user: { _id: "2", fullName: "Priya Sharma", email: "priya@example.com", mobile: "+91 98765 43210", gender: "Female" },
    userId: "#1002", docNumber: "XXXX XXXX 4321", dob: "15/08/1995", gender: "Female",
    fathersName: "Ramesh Sharma",
    address: "#456, Park Street, Mumbai - 400001",
    state: "Maharashtra", pincode: "400001", age: 26,
    verifiedAt: "2024-03-17 10:30 AM",
    otpVerified: true, uidaiValidated: true, biometricMatch: true, autoApproved: true,
  },
  {
    _id: "v3",
    user: { _id: "4", fullName: "Amit Verma", email: "amit@example.com", mobile: "+91 98765 43210", gender: "Male" },
    userId: "#1003", docNumber: "XXXX XXXX 4321", dob: "15/08/1995", gender: "Male",
    fathersName: "Suresh Verma",
    address: "#789, FC Road, Pune - 411001",
    state: "Maharashtra", pincode: "411001", age: 30,
    verifiedAt: "2024-03-17 10:30 AM",
    otpVerified: true, uidaiValidated: true, biometricMatch: true, autoApproved: true,
  },
  {
    _id: "v4",
    user: { _id: "5", fullName: "Sneha Patel", email: "sneha@example.com", mobile: "+91 98765 43210", gender: "Female" },
    userId: "#1004", docNumber: "XXXX XXXX 4321", dob: "15/08/1995", gender: "Female",
    fathersName: "Mahesh Patel",
    address: "#321, SG Highway, Ahmedabad - 380015",
    state: "Gujarat", pincode: "380015", age: 27,
    verifiedAt: "2024-03-17 10:30 AM",
    otpVerified: true, uidaiValidated: true, biometricMatch: true, autoApproved: true,
  },
  {
    _id: "v5",
    user: { _id: "6", fullName: "Karthik Iyer", email: "karthik@example.com", mobile: "+91 98765 43210", gender: "Male" },
    userId: "#1005", docNumber: "XXXX XXXX 4321", dob: "15/08/1995", gender: "Male",
    fathersName: "Rajan Iyer",
    address: "#654, Anna Nagar, Chennai - 600040",
    state: "Tamil Nadu", pincode: "600040", age: 29,
    verifiedAt: "2024-03-17 10:30 AM",
    otpVerified: true, uidaiValidated: true, biometricMatch: true, autoApproved: true,
  },
];

export const RECENT_USERS = [
  { fullName: "Priya Sharma",  email: "priya@example.com",  status: "verified", time: "2 hours ago"  },
  { fullName: "Rahul Verma",   email: "rahul@example.com",  status: "verified", time: "3 hours ago"  },
  { fullName: "Anjali Patel",  email: "anjali@example.com", status: "verified", time: "5 hours ago"  },
  { fullName: "Amit Kumar",    email: "amit@example.com",   status: "verified", time: "1 day ago"    },
  { fullName: "Sneha Singh",   email: "sneha@example.com",  status: "verified", time: "1 day ago"    },
];

export const USER_GROWTH_DATA = [
  { day: "Mon", newUsers: 120, verified: 90  },
  { day: "Tue", newUsers: 152, verified: 110 },
  { day: "Wed", newUsers: 190, verified: 130 },
  { day: "Thu", newUsers: 145, verified: 100 },
  { day: "Fri", newUsers: 210, verified: 160 },
  { day: "Sat", newUsers: 175, verified: 140 },
  { day: "Sun", newUsers: 195, verified: 150 },
];

export const SUBSCRIPTION_GROWTH_DATA = [
  { month: "Jan", subs: 160 },
  { month: "Feb", subs: 185 },
  { month: "Mar", subs: 210 },
  { month: "Apr", subs: 310 },
  { month: "May", subs: 380 },
  { month: "Jun", subs: 460 },
];